import Header from "@/components/layout/header";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter, Roboto_Mono } from "next/font/google";

export const metadata: Metadata = {
  title: "One Kingdom",
  description: "Generated by create next app",
};


export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      {children}
    </>
  );
}
